#! /usr/bin/env python3

"""
---------------------------------------------------------------------------------------------
# File    : build.py
# Author  : Neo.H
# Date    : Sep 14, 2018
# Version : v1.00
---------------------------------------------------------------------------------------------
This is a build program for build up the simulation ENV. For now, mainly to provide the
ENV environments, such as PROJ_HOME, PROJ_NAME etc. This program will provide the variables
by printing these VARs to the screen, and the calling tool will access all these vars.
---------------------------------------------------------------------------------------------
Print Formats:
	-- PROJ_HOME=<Absolute Path>
---------------------------------------------------------------------------------------------
Variables need to provide in current version:
	-- PROJ_HOME
---------------------------------------------------------------------------------------------
"""
